language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE volcanoes;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: qrtJ01j5VQ67riztQUjT55ef1qnrOx3zn6DciwRl7kclMhRKRpc/BPHYvCTbj2My+ykreXU0QoHjCktMmJmEhqhnXPRjsHqI/ycAANNd3mA7fhLpgiryFrBP+Z2m9m6z+xcOV9IVKPKVerYyQyY0prjLggCSxsBzVC+T282GyqvSCL6H2OkgnT5cnKPmujdH1otPeckXz23iuacKGet6p8ngeEW158C9Z/EQTVZSkJf5r3T6pvIvSa95K5Y6qivbhmFlkwokch/mkEowD6HdUEENN1KMyg1gwIdN+2xLORtpqewUl3CLE+0MZMYtRwn121KuBlyNIormTKDJs9x+I7olzz+6iFKVxitiHbQ6uhc1y0Ws8W8EShAstOh1xay93rkoZuebJgkF/N8jvtong/0mYl/TyvKTBYtKjuNrW5il4r81XW3qsZAia/D/jlKoSQUKgagj/7dIiXVkHFhVOU/odXZVQHCWI7/hKjRt7gAw0vh4X+9BsKXmVIdbwyJ5qXP8UCG/v/LDk1XIyo7JfPUEU0co+OezuejJHZmFObCxE0Cisk7xq1KJiaunyfSS3BlZxqGuKiFRwKouHWozNOA796BuJulhkzK9nacnzbg55cs0T5KAPypexj4id12Cirl8iieTwCAqEVJguG+rPyWZL1m8oCMDh2ecxZUo/eU=
  app: byob-volcanoes-krishel
  skip_cleanup: true
