language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE volcanoes;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: X5nAUrJ6VDgqfIEn+19GxE6z1ZQoZ+TiKx9S2ceXE04f9rluscTzgSTPbEKhu2DvWJKLzWl7bJJd5EZHEoMwsBoTpTJ+lycVuaw5XBjQdUZONww4ilLjX1sdEE624cMD4LV+PR/z5JczDTjkqgnJ1MMcDe1OfGxzZFOzgjhbK56WXIlxWO1U3WVSjpaeErhQCSj/Ti2JAN5dBpeGmwe2BhqsLK3PgBzv9Sjl6KHBxdrcaqAZvaVM+3n0NJK0Di5u3WZQvNNNXF2O1EIE8O8YpNnsHvthEbujYX6TLQqqeFxO9sdQgNjQELN2XvTmBFNpfA9iLjiGkf5U+DXUPMZFZT4Fl4EQHk3DdfCwUqmfgbq1zy2BGN2Cu87r7PoOd3cJ7xCJyTp2cVJQD6LfTgeUO7v5VeSwMwtFIb26h3dCho+407RnSz7JqOnutpGOpLlJg2yYp/cCEA8rbjehc/A1Emq/2QLV6YP8q2TJkT7f3qwKVJKqmgdU80eTPZi/SOyU7GttWIUO9QQdu9tH/rK8HM4DwRYXYoLGJy0Ojn4X5NE8obTV4V1IW1pGd4pXTfwQPfiB7PaJ2ngmwZwhVgO87hBoRKvAPS1MxjwoWi4A1U/gKQ5m2+NffMiyamBCIeD2xyx8h+aNmEMg1iS06rm3MJL0JJ3ehbL2gy2oYJjG4cs=
  app: byob-volcanoes-krishel
  skip_cleanup: true
  